### PR TITLE
Firefox 60 compatibility fixes (for Zotero 5.0.78)

### PR DESCRIPTION
**Pull request by dstillman**
Note that this won't work with versions of Zotero before 5.0.78, including their Juris-M equivalents, but I don't think it's worth the extra effort to maintain compatibility for a few more days.

### CODE REVIEW

**Comment by fbennett** [comment]
Thanks!

**Comment by dstillman** [comment]
Actually, hang on — there's still some breakage here with RTF mode.

**Comment by fbennett** [comment]
No worries, holding...

**Comment by dstillman** [comment]
Is there a good reason this overrides the existing RTF Scan functionality instead of just creating a separate menu option for ODF Scan? This code duplicates and overrides all of the RTF Scan stuff, but that means that if we fix something in RTF Scan the fixes won't make it to here.

We could fix the RTF Scan issues here, but it might make more sense just to have this be a separate thing…

**Comment by dstillman** [comment]
(Put another way, as far as I can tell the ODF Scan stuff is fixed, and I'm not sure why it makes sense to spend time fixing RTF Scan when that already works in Zotero.)

**Comment by dstillman** [comment]
In fact, RTF mode was already broken in Zotero 5.0.77 in version 2.0.41 of the plugin, which has been out for a year… So this should definitely just be a separate menu option.

**Comment by retorquere** [comment]
build.py is now compatible with Py35 (https://github.com/Juris-M/zotero-odf-scan-plugin/pull/36)

**Comment by fbennett** [comment]
I was thinking the same thing. Haven't looked at the code in years,
but there's no good reason to clone all of that code. I'll look at it
and try to separate the two. Might happen this weekend, maybe a bit
after.

**Comment by dstillman** [comment]
I submitted a [pull request](https://github.com/Juris-M/zotero-odf-scan-plugin/pull/35) that removes the RTF override 15 hours ago, and it's also linked above.

**Comment by fbennett** [comment]
Thanks - will take a look after breakfast.

FB

**Pull request merged**
