### PR TITLE
basics for build setup

### PR DESCRIPTION
**Pull request by retorquere**
(plus some general cleanup of tabs)

### CODE REVIEW

**Comment by retorquere** [comment]
basics for a build setup. `npm version patch` can be used to manage versions.

**Comment by adam3smith** [comment]
yeah, this is great, thanks so much! Also like that this stops using the gh-pages branch.

**Comment by retorquere** [comment]
Cool. I don't really know what all the rest in jm-sh does but I think these two scripts bring us mostly there already. Technically possible to replace the python script with a node script, but async is an unnecesary burden for shell scripting. The scripts in package.json depend on [github-release](https://github.com/aktau/github-release) -- again technically possible to replace with python code, but this is quick and easy. Python code could do more stringent tests like bailing if a release already exists (github-release does not bail on this but will bail on re-upload of the asset)

**Comment by retorquere** [comment]
(the version in package.json is bogus, I was using it for testing, should be replaced with an actual version of course)

**Comment by adam3smith** [comment]
this can absolutely be lightweight -- we're not not planning on BBT-level release frequencies here. And I at least much prefer this in python to npm

**Comment by retorquere** [comment]
There are only two reasons why npm is involved right now:

1. `npm version patch` takes care of version bumping and checks beforehand all files are checked in.
2. The version number needs to live somewhere. If it were all python I'd probably have settled on making install.rdf authoritative, but see 1.

**Comment by adam3smith** [comment]
thanks for doing this -- I don't have a suitable testing set-up on my work machine, so test&merge will happen tonight or over the weekend.

**Comment by retorquere** [comment]
In that case let me push a few more commits to make it a fully working setup.

**Comment by retorquere** [comment]
Should work now

**Comment by retorquere** [comment]
There was more than just the promise, the observer message that the scanner was waiting for is no longer being fired, and it's no longer necessary to listen for it even if it were in Z5. The current state installs the translator successfully.

**Comment by adam3smith** [comment]
I checked out your branch, build using the script with the --beta flag (works great), the .xpi looks good as far as I can tell, installs and installs the translator, but then I get:

XML Parsing Error: undefined entity
Location: chrome://rtf-odf-scan-for-zotero/content/rtfScan.xul
Line Number 8, Column 1:<wizard xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"

I poked around a bit, but the error doesn't make any sense to me, especially since you didn't touch that script. Any idea?

**Comment by retorquere** [comment]
The DTDs were missing because python's `glob.glob` isn't recursive by default even if you specify `**`. Fixed now.

**Comment by adam3smith** [comment]
Great, thanks!

**Comment by retorquere** [comment]
jm-sh and build.sh can probably be removed now, but I didn't want to delete stuff without knowing if there's information contained in those scripts worth retaining.

**Pull request merged**
